### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by yatesco** [melvic-ybanez/esena#1]
Hi there - I've just checked it out (* 5584370 (HEAD -> main, origin/main, origin/HEAD) Incorporate refraction into shade-hit) but it won't compile due to:

```scala
sbt:esena> test
[info] Compiling 37 Scala sources to /Users/coliny/Dev/esena/target/scala-2.13/classes ...
[error] /Users/coliny/Dev/esena/src/main/scala/com/melvic/esena/shapes/Sphere.scala:4:8: value Intersections is not a member of object com.melvic.esena.rays.Intersection
[error] import com.melvic.esena.rays.Intersection.Intersections
[error]        ^
[error] /Users/coliny/Dev/esena/src/main/scala/com/melvic/esena/shapes/Sphere.scala:17:53: not found: type Intersections
[error]   override def localIntersect(transformedRay: Ray): Intersections = {
[error]                                                     ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed 20 Sep 2021, 09:08:01
```

I'm only being nosy about Scala so not urgent at all, I'm just mentioning it in passing :-)

**Comment by melvic-ybanez** [comment]
Hi @yatesco thanks for reporting. I pushed new changes. This should be fixed by now.

**Comment by yatesco** [comment]
My pleasure - it compiles now. 

I noticed that Metals didn't provide any functionality (goto definition, find references etc.) when there was a compilation failure - is this common? Or maybe I haven't configured it properly. I tried in emacs, neovim, and vscode.

**Comment by melvic-ybanez** [comment]
I usually just use Intellij so I'm not really sure how common that case is with Metals.
